#!/bin/bash

## Make sure we are in the script directory
ScriptDIR=$(cd `dirname $0` && pwd)
if [ $ScriptDIR != $PWD ]; then
   echo "Ce script doit être executé depuis son dossier" 1>&2
   exit
fi

#On récupère le nombre de sessions actives de Yane
C=`sudo ./yane  -l | wc -l`

if [ "$C" == "0" ] ; then
  echo "Aucune session n'est lancée pour en lancer une executez :"
  echo "   START"

elif [ "$C" -gt "1" ] ; then
  echo "Trop de sessions ouvertes !! "
  echo "Pour voir les ID de session :"
  echo "   sudo yane -l"
  echo "Pour forcer la fermuture d'une session :"
  echo "   sudo yane -s <ID SESSION> -k"

else

