#!/bin/bash

#interface Routeur FAI
ip addr add 17.0.1.2/24 dev eth0
ip link set dev eth0 up

#interface Serveur WEB
ip addr add 10.0.0.1/24 dev eth1
ip link set dev eth1 up

#interface Serveur FTP
ip addr add 11.0.0.1/24 dev eth2
ip link set dev eth2 up

#interface Serveur DNS
ip addr add 12.0.0.1/24 dev eth3
ip link set dev eth3 up
