#!/bin/bash

#interface Routeur FAI
ip addr add 17.0.2.1/24 dev eth0
ip link set dev eth0 up

#interface client
ip addr add 192.168.1.1/24 dev eth1
ip link set dev eth1 up

#activation du routage
echo 1 > /proc/sys/net/ipv4/ip_forward

#ajout de la route par défaut 
ip r a default via 17.0.2.2

#FIREWALL

#NAT
iptables -t nat -A POSTROUTING -s 192.168.1.0/24 -j MASQUERADE
 
#DHCP
/etc/init.d/isc-dhcp-server start
